package org.dromara.payment.constant;

/**
 * 支付事件中心常量。
 */
public interface PaymentConstants {

    Long DEFAULT_MERCHANT_ID = 1900000000000000001L;
    Long MERCHANT_ADMIN_ROLE_ID = 1900200000000000001L;
    Long MERCHANT_APPLICANT_ROLE_ID = 1900200000000000002L;
    Long PLATFORM_REVIEWER_ROLE_ID = 1900200000000000003L;
    Long MERCHANT_OWNER_ROLE_ID = 1900200000000000004L;
    Long MERCHANT_FINANCE_ROLE_ID = 1900200000000000005L;
    Long MERCHANT_DEVELOPER_ROLE_ID = 1900200000000000006L;
    Long MERCHANT_VIEWER_ROLE_ID = 1900200000000000007L;
    Long DEFAULT_DEPT_ID = 1761000000000000100L;
    String DEVICE_ID_ATTRIBUTE = "paymentDeviceId";
    String MERCHANT_ID_ATTRIBUTE = "paymentMerchantId";
    String MERCHANT_API_KEY_ATTRIBUTE = "paymentMerchantApiKeyId";
    String DEVICE_STATUS_ENABLED = "0";
    String DEVICE_STATUS_DISABLED = "1";
    String EVENT_STATUS_RECEIVED = "RECEIVED";
    String EVENT_STATUS_REVIEWED = "REVIEWED";
    String EVENT_STATUS_IGNORED = "IGNORED";
    String EVENT_STATUS_MATCHED = "MATCHED";
    String EVENT_STATUS_CONFLICT = "CONFLICT";
    String ORDER_STATUS_PENDING = "PENDING";
    String ORDER_STATUS_PAID = "PAID";
    String ORDER_STATUS_EXPIRED = "EXPIRED";
    String ORDER_STATUS_CANCELLED = "CANCELLED";
    String ORDER_STATUS_CONFLICT = "CONFLICT";
    String CONFIRMATION_UNCONFIRMED = "UNCONFIRMED";
    String CONFIRMATION_NOTIFICATION = "NOTIFICATION";
    String CONFIRMATION_MANUAL = "MANUAL";
    String CONFIRMATION_RECONCILED = "RECONCILED";
    String TRANSACTION_OBSERVED = "OBSERVED";
    String TRANSACTION_MATCHED = "MATCHED";
    String TRANSACTION_CONFIRMED = "CONFIRMED";
    String TRANSACTION_RECONCILED = "RECONCILED";
    String TRANSACTION_REJECTED = "REJECTED";
    String TRANSACTION_REVERSED = "REVERSED";
    String SLOT_ACTIVE = "ACTIVE";
    String SLOT_COOLING = "COOLING";
    String SLOT_RELEASED = "RELEASED";
    String MERCHANT_ONBOARDING = "ONBOARDING";
    String MERCHANT_ACTIVE = "ACTIVE";
    String MERCHANT_SUSPENDED = "SUSPENDED";
    String MERCHANT_CLOSED = "CLOSED";
    String MEMBER_OWNER = "OWNER";
    String MEMBER_ADMIN = "ADMIN";
    String MEMBER_FINANCE = "FINANCE";
    String MEMBER_DEVELOPER = "DEVELOPER";
    String MEMBER_VIEWER = "VIEWER";
    String DUPLICATE_STATUS_NONE = "NONE";
    String DUPLICATE_STATUS_SUSPECTED = "SUSPECTED";
    String DUPLICATE_STATUS_CONFIRMED = "CONFIRMED";
    String DUPLICATE_STATUS_EXCLUDED = "EXCLUDED";
    int WEBHOOK_SCHEMA_VERSION = 2;
}
